[sst2]
engine = 'huggingface'
type = 'text'
path = 'stanfordnlp/sst2'
split_train = 'train'
split_validation = 'validation'
input = 'sentence'
target = 'label'

[imdb]
engine = 'huggingface'
type = 'text'
path = 'stanfordnlp/imdb'
split_train = 'train'
split_validation = 'test'
input = 'text'
target = 'label'